name: base_app
description: A new Flutter project.

publish_to: "none"

version: 0.0.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: 7.3.0

  dartz: 0.10.1
  json_annotation: 4.8.0
  equatable: 2.0.5
  go_router: 7.1.1
  intl: 0.18.1
  dio: 5.3.0
  flutter_secure_storage: 8.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: 2.3.3
  json_serializable: 6.6.1
  mockito: 5.4.0
  faker: ^2.1.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/mocks/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
