name: base_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: 7.3.0

  json_annotation: 4.8.0
  equatable: 2.0.5
  go_router: 7.1.1
  intl: 0.18.1
  firebase_core: 2.14.0
  cloud_firestore: ^4.8.2
  firebase_auth: 4.6.3
  google_sign_in: 6.1.4

  flutter_secure_storage: 8.0.0
  carousel_slider: 4.2.1
  flutter_native_splash: 2.3.6

dev_dependencies:
  flutter_lints: 2.0.0
  build_runner: 2.3.3
  json_serializable: 6.6.1
  mockito: 5.4.2
  fake_cloud_firestore: ^2.4.1+1
  faker: 2.1.0

  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: "assets/images/splash_screen.png"
  color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/mocks/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
